### ISSUE TITLE
I am staff but not being reported to beacon as such.

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-beacon-component#62]
![screen shot 2015-07-03 at 11 21 40](https://cloud.githubusercontent.com/assets/825088/8497518/cc454c24-2175-11e5-8e8a-3bad4df8f388.png)

The last erights ID: 8329133 is *me* :scream:

**Comment by matthew-andrews** [comment]
https://keen.io/project/5486efb559949a0a311510fa/explorer?query%5Bevent_collection%5D=cta&query%5Banalysis_type%5D=count&query%5Btarget_property%5D=user.erights&query%5Bgroup_by%5D=user.erights&query%5Btimezone%5D=UTC&query%5Bfilters%5D%5B0%5D%5Bproperty_name%5D=meta.domPath&query%5Bfilters%5D%5B0%5D%5Boperator%5D=contains&query%5Bfilters%5D%5B0%5D%5Bproperty_value%5D=organisation-summary&query%5Bfilters%5D%5B0%5D%5Bcoercion_type%5D=String&query%5Bfilters%5D%5B1%5D%5Bproperty_name%5D=user.isStaff&query%5Bfilters%5D%5B1%5D%5Boperator%5D=eq&query%5Bfilters%5D%5B1%5D%5Bproperty_value%5D=false&query%5Bfilters%5D%5B1%5D%5Bcoercion_type%5D=Boolean&visualization%5Bchart_type%5D=barchart

**Comment by matthew-andrews** [comment]
cc @commuterjoy @adam

**Comment by adambraimbridge** [comment]
Odd. It seems that user.isStaff isn't 100% reliable.
![image](https://cloud.githubusercontent.com/assets/224547/8498260/8d0686de-217c-11e5-9a48-a1d10fb9af57.png)
https://keen.io/project/5486efb559949a0a311510fa/explorer?query%5Bevent_collection%5D=cta&query%5Banalysis_type%5D=count&query%5Btarget_property%5D=user.isStaff&query%5Bgroup_by%5D=user.isStaff&query%5Btimezone%5D=UTC&query%5Bfilters%5D%5B0%5D%5Bproperty_name%5D=user.erights&query%5Bfilters%5D%5B0%5D%5Boperator%5D=eq&query%5Bfilters%5D%5B0%5D%5Bproperty_value%5D=8329133&query%5Bfilters%5D%5B0%5D%5Bcoercion_type%5D=Number&query%5Btimeframe%5D=this_14_days&visualization%5Bchart_type%5D=JSON

**Comment by matthew-andrews** [comment]
I would say approximately 2.6% reliable.

**Comment by adambraimbridge** [comment]
Todo: Check the graphite dashboard to detect cases of false isStaff negatives

**Comment by matthew-andrews** [comment]
gonna change my email address
